Add support for Listing of Waivers (Issue #17)
csu-chhs/SmartWaiver.Net pull request #75
Opened 2023-03-04 19:25 UTC by catapedamania

Some updates to v4.2.11

2023-03-07 18:03 UTC, dstegelman requested changes

2023-03-07 18:03 UTC, dstegelman commented on SmartWaiver.Net/Interfaces/IWaiverClient.cs
> -        Task<SignedWaiver> GetSignWaiverAsync(string waiverId, bool includePdf = false);
It looks like you removed the Async GetSignWaiverAsync method?  That should still remain.

2023-03-08 11:52 UTC, catapedamania commented on SmartWaiver.Net/Interfaces/IWaiverClient.cs
> -        Task<SignedWaiver> GetSignWaiverAsync(string waiverId, bool includePdf = false);
Sorry, went missing when I renamed from Sign to Signed and added the new list function

2023-03-08 21:56 UTC, dstegelman approved these changes

2023-03-08 21:57 UTC, dstegelman commented
Thank you for your contribution!

2023-03-08 21:57 UTC, merged