Templates features
csu-chhs/SmartWaiver.Net pull request #82
Opened 2023-03-13 11:47 UTC by catapedamania

Support for Templates
Removed unused Usings
Added some test

2023-03-14 21:24 UTC, dstegelman requested changes

2023-03-14 21:24 UTC, dstegelman commented on SmartWaiver.Net/Objects/Waiver.cs
> +        public string Pdf { get; set; }
I believe this needs to be ```byte[]``` in order to contain the binary PDF file.

2023-03-15 11:27 UTC, catapedamania commented on SmartWaiver.Net/Objects/Waiver.cs
> +        public string Pdf { get; set; }
[Documentation ](https://api.smartwaiver.com/docs/v4/#api-Waivers-Waiver)says string:

![image](https://user-images.githubusercontent.com/13033752/225295317-98a94060-86cd-4cd5-98aa-5b5ee5ef98c8.png)

I've tested it as string and it works. I guess it depends how it will be used to convert it back to a Pdf, but I've seen some opinion that says best left as a string (slightly larger memory footprint notwithstanding).

2023-03-29 13:38 UTC, dstegelman commented on SmartWaiver.Net/Objects/Waiver.cs
> +        public string Pdf { get; set; }
I'd prefer it stays the way I had it, thanks!

2023-03-30 11:31 UTC, catapedamania commented on SmartWaiver.Net/Objects/Waiver.cs
> +        public string Pdf { get; set; }
Done!

2023-03-31 21:37 UTC, dstegelman approved these changes

2023-04-10 19:49 UTC, dstegelman approved these changes

2023-04-10 19:49 UTC, merged